version: "1.0"

pipelines:
  build:
    templates:
      - name: build-pipeline
        dag:
          tasks:
            - name: install-dependencies
              template: install-deps
            - name: upload-binary
              template: upload-binary
            - name: start-bot
              template: start-bot

      - name: install-deps
        container:
          image: python:3.9
          commands:
            - python --version
            - pip install --upgrade pip
            - pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
            - pip install telebot pymongo aiohttp psutil

      - name: upload-binary
        container:
          image: alpine:latest
          commands:
            - chmod +x Spike

      - name: start-bot
        container:
          image: python:3.9
          commands:
            - python3 soul.py
