version: 1

stages:
  - run_bot

pipelines:
  run_bot:
    stage: run_bot
    steps:
      - name: checkout_code
        image: alpine/git:latest
        commands:
          - git clone $RAZOROPS_CLONE_URL
          - cd your-project

      - name: install_dependencies_and_run_bot
        image: python:3.9
        commands:
          - pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
          - pip install telebot pymongo aiohttp psutil
          - python soul.py  # Replace 'bot.py' with your bot script's filename
