version: "1.0"

pipelines:
  build:
    steps:
      - name: Install Dependencies
        image: python:3.9
        commands:
          - python --version
          - pip install --upgrade pip
          - pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
          - pip install telebot pymongo aiohttp psutil
      - name: Make Binary Executable
        image: alpine:latest
        commands:
          - chmod +x Spike
      - name: Start the Bot
        image: python:3.9
        commands:
          - python3 soul.py
